### ISSUE TITLE
Fail to mount key drive

### ISSUE THREAD

**Issue by ste7677** [fearedbliss/bliss-initramfs#23] opened 2018-11-07 16:30 UTC
USB key drives: Having 2 identical named USB drives (disk labeled "BOOTKEY" here), one works and the other one will fail to mount on boot. Note: The USB sticks are from different vendors!

Error on boot: 

mount: mounting /dev/disk/by-label/BOOTKEY on /mnt/key failed: No such file or directory
[#] Failed to mount you key drive

(init script, Line 499)

as soon as I am into initrd rescue shell, I can mount without any errors by issuing the exact command as in the init script:

mount /dev/disk/by-label/BOOTKEY /mnt/key

Works!

Could it be udev related? Any ideas?

btw: the reason for me to use DISK-BY-LABEL is to have multiple copies of my master key USB sticks available.

**Comment by fearedbliss** [comment] 2018-11-07 16:50
I no longer work on this project, please fork :).

**Comment by fearedbliss** [comment] 2018-11-08 12:33
Correct. I use debian on my server, Fedora on my work laptop and my other home laptop, and windows on my home desktops.

**Comment by ste7677** [comment] 2018-11-08 13:11
I used your stuff a lot, coming from your "install ifs on gentoo" tutorial. Thanks for the work :)

However, I assume you will also discontinue to work on the zfs rescue disk? Are there any alternatives or could you maybe put the sources to github?

**Comment by fearedbliss** [comment] 2018-11-08 13:32
@ste7677 I stopped making the isos months ago haha. The sources for the tools have always been available, it's just a matter of actually learning how to use them. Check the sysresccd-moddat repo.

**Comment by ste7677** [comment] 2020-02-04 09:06
@fearedbliss Great to see you back working on bliss-initramfs - thank you :) ! I can drop my fork now. Back on gentoo too?

**Comment by fearedbliss** [comment] 2020-02-04 11:40
@ste7677 haha that is correct in back on Gentoo as well. As for the original problem in this post, I'll need to take a look but from reading the message it seems that this is a problem due to your workflow. I'm not surprised it would fail if you used the same label everywhere. You should use another label or better yet, has the unique identier of the flash drives. Maybe by id? That's usually what I recommend.

**Comment by ste7677** [comment] 2020-02-04 14:00
I will test the original issue as soon as I find some time and report back. As far as I remember, some sticks would work, some would not (different models). It seemed they were just slower recognized. 

However, I manually fixed it back then with an additional udevdev trigger / sleep combo at init::PrepareForLuks() and it works stable ever since, using 1 of 3 copies of the key usb stick - all labeled the same.

see https://github.com/ste7677/bliss-initramfs/commit/ae358f6552c2625b6409d5f6ed324664965cbcb2

Take care and have fun @ gentoo again ;-)

**Comment by fearedbliss** [comment] 2020-02-04 14:11
@ste7677 ah I see what you mean, I thought to you were plugging in two USBs with the same label at the same time haha. Yea if they are just plugged in one at a time with the same label it should work. And that definitely sounds correct that it may be due to the USB speeds and we may just need to give it more time to detect. There is actually some code that is suppose to try and detect / re detect the drives. I'll re open this ticket for now and you can give me feedback and all of that since this isn't something I can reproduce probably due to the different behavior with different USBs

**Comment by ste7677** [comment] 2020-02-04 14:22
@fearedbliss Don't worry, just close the ticket. I don't even think I would have those old sticks available anymore. 

However, taking a quick look at your new release I see PrepareForLuks() hasn't changed. I might be a good idea to insert the 3 lines from the patch above anyway. Should not do any harm, just re-triggers and adds a couple seconds delay. Might be saver. Just take a look.

**Comment by fearedbliss** [comment] 2020-02-04 14:23
Yup I took a look at it and probably will merge that in, but was hoping you still had those old flash drives for further testing haha

**Comment by fearedbliss** [comment] 2020-06-25 20:05
Closing Issue

**Closed by fearedbliss** 2020-06-25 20:05 UTC
