### ISSUE TITLE
shutil.Error: [Errno 21] Is a directory

### ISSUE THREAD

**Issue by MrGeorgen** [fearedbliss/bliss-initramfs#32] opened 2020-09-04 21:47 UTC
when I try to run bliss-initramfs 8.1.0, I get the following error:
```
[*] Performing finishing steps ...
Traceback (most recent call last):
  File "/sbin/bliss-initramfs", line 61, in <module>
    Main.start()
  File "/sbin/bliss-initramfs", line 55, in start
    Core.LastSteps()
  File "/opt/bliss-initramfs/pkg/libs/Core.py", line 490, in LastSteps
    shutil.copytree(var.modprobeDirectory, var.temp + var.modprobeDirectory)
  File "/usr/lib/python3.7/shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('/etc/modprobe.d', '/home/mrgeorgen/bi-443694881/etc/modprobe.d', "[Errno 21] Is a directory
```
my config:
```
{
    "firmware": {
        "use": 0,
        "copyAll": 0,
        "files": [],
        "directories": []
    },
    "modules": {
        "files": []
    },
    "base": {
        "files": [
            "/bin/busybox",
            "/bin/bash",
            "/bin/egrep",
            "/bin/fgrep",
            "/bin/grep",
            "/usr/bin/loadkeys",
            "/bin/kmod",
            "/bin/udevadm"
        ],
        "kmodLinks": [
            "depmod",
            "insmod",
            "lsmod",
            "modinfo",
            "modprobe",
            "rmmod"
        ],
        "udevProvider": "/sbin/udevd"
    },
    "zfs": {
        "files": [
            "/sbin/fsck.zfs",
            "/sbin/mount.zfs",
            "/sbin/zfs",
            "/sbin/zpool"
        ],
        "optionalFiles": [
            "/sbin/zdb",
            "/sbin/zhack",
            "/sbin/zinject",
            "/sbin/zstreamdump",
            "/sbin/ztest"
        ],
        "useMan": 0,
        "manFiles": [
            "/usr/share/man/man5/spl-module-parameters.5.bz2",
            "/usr/share/man/man1/zhack.1.bz2",
            "/usr/share/man/man1/ztest.1.bz2",
            "/usr/share/man/man5/vdev_id.conf.5.bz2",
            "/usr/share/man/man5/zfs-events.5.bz2",
            "/usr/share/man/man5/zfs-module-parameters.5.bz2",
            "/usr/share/man/man5/zpool-features.5.bz2",
            "/usr/share/man/man8/fsck.zfs.8.bz2",
            "/usr/share/man/man8/mount.zfs.8.bz2",
            "/usr/share/man/man8/vdev_id.8.bz2",
            "/usr/share/man/man8/zdb.8.bz2",
            "/usr/share/man/man8/zfs.8.bz2",
            "/usr/share/man/man8/zinject.8.bz2",
            "/usr/share/man/man8/zpool.8.bz2",
            "/usr/share/man/man8/zstreamdump.8.bz2"
        ]
    },
    "luks": {
        "useKeyfile": 0,
        "keyfilePath": "/crypto_keyfile.bin",
        "useDetachedHeader": 0,
        "detachedHeaderPath": "/crypto_header.bin",
        "files": [
            "/sbin/cryptsetup",
            "/usr/bin/gpg",
            "/usr/bin/gpg-agent",
            "/sbin/dmsetup"
        ]
    },
    "systemDirectory": {
        "bin": "/bin",
        "sbin": "/sbin",
        "lib": "/lib",
        "lib64": "/lib64",
        "etc": "/etc"
    },
    "preliminaryBuildBinaries": [
        "/bin/cpio",
        "/sbin/depmod"
    ],
    "initrdPrefix": "initrd-",
    "modulesDirectory": "/lib/modules",
    "firmwareDirectory": "/lib/firmware",
    "udevConfigDirectory": "/etc/udev",
    "udevLibDirectory": "/lib/udev",
    "modprobeDirectory": "/etc/modprobe.d"
}
```

**Comment by fearedbliss** [comment] 2020-09-04 22:17
Hey there, I have a few questions:

- Are you running Gentoo Linux?
- What's the output of `ls -l /etc/ | grep modprobe.d`?
- What's the output of `ls -l /etc/modprobe.d`?
- Could you try and re-run this with the latest version of the application (9.2.0)? If on Gentoo, you can unmask it by doing:

`echo "=sys-kernel/bliss-initramfs-9.2.0 ~amd64" >> /etc/portage/package.accept_keywords`
`emerge -au bliss-initramfs`

After look at the code again, and running some experiments, I was unable to reproduce it. The code already checks to see that `/etc/modprobe.d` is a directory before attempting to copy it with the `shutil.copytree`. The interesting is that that error is coming from the `shutil.copytree`, which means python already said it was a directory and thus should copy that directory. So for the error from shutil to be that it is a directory, is weird. Could you try running it with Python 3.8.5 which is the latest stable on Gentoo?

**Comment by fearedbliss** [comment] 2020-09-04 22:32
I also checked the `shutil.copytree` documention for Python 3.7 and 3.8 and there have been some new things added to this function:

```


Changed in version 3.8: Platform-specific fast-copy syscalls may be used internally in order to copy the file more efficiently. See Platform-dependent efficient copy operations section.

New in version 3.8: The dirs_exist_ok parameter.
```

Both could affect you in this case. The first may have some type of fix that works on my end (But I've used bliss-initramfs on 3.7 and it's always worked for me), and the second I can try to use in bliss-initramfs to see if it fixes it. If you upgrade to 3.8.5 and it doesn't work, could you try to add the following to that particular line in `pkg/libs/Core.py` line 490:

It should look like this for you at the moment:

`shutil.copytree(var.modprobeDirectory, var.temp + var.modprobeDirectory)`

try to change it to:

`shutil.copytree(var.modprobeDirectory, var.temp + var.modprobeDirectory, dirs_exist_ok=True)`

Only do that if it doesn't work when you update to 3.8.5.

**Comment by MrGeorgen** [comment] 2020-09-05 15:14
I am running bedrock linux with gentoo as my strata for most packages. Normally I only run into problems when programs from different strata try to interact with each other. bedrock linux uses a FUSE filesystem for /etc to make some config files available from different strata. It could be possible, that this filesystem causes problems. I never had any problems with it except high cpu usage, but it is possibility because I seam to be the only one with this error.  
The output of the commands:
```
[mrgeorgen@gentoo-mrg ~]$ ls -l /etc/ | grep modprobe.d 
drwxr-xr-x 2 root root       4096 31. Aug 19:34 modprobe.d
[mrgeorgen@gentoo-mrg ~]$ ls -l /etc/modprobe.d 
insgesamt 12 
-rw-r--r-- 1 root root 1186 10. Feb 2020  aliases.conf 
-rw-r--r-- 1 root root 1028 10. Aug 22:28 alsa.conf 
-rw-r--r-- 1 root root  122 10. Feb 2020  i386.conf 
```
I have not tried to update python, I'll do it now

**Comment by MrGeorgen** [comment] 2020-09-05 17:50
updating python does not help

**Comment by fearedbliss** [comment] 2020-09-05 19:33
Since bliss initramfs is designed for Gentoo Linux and Gentoo Linux users including myself are not experiencing this issue, and also because upon inspecting the code and the library everything is correct, I’m closing this issue. If you find a simple way to get it to work for yourself that could be upstreamed, I would be happy to take a look and merge in that work to accommodate you.

**Comment by MrGeorgen** [comment] 2020-09-05 22:22
After changing the critical line to: `            subprocess.call(["cp", "-r" , var.temp + var.modprobeDirectory, var.modprobeDirectory])` I get the ouput: `no such file or directory`
I checked and there is indeed no directory under bi-*/etc/modprobe.d

**Comment by fearedbliss** [comment] 2020-09-05 22:27
That’s correct. The shuttle.copytree command requires that the target directory does not exist by default. Starting with py 3.8, I could specify the variable mentioned above so that it doesn’t throw an exception when the directory already exists. 

For our case, it’s guaranteed that the directory won’t exist which is the intended behavior before attempting to copy the modprobe dir into the initramfs.

From the api:

> Recursively copy an entire directory tree rooted at src to a directory named dst and return the destination directory. dirs_exist_ok dictates whether to raise an exception in case dst or any missing parent directory already exists.

**Comment by MrGeorgen** [comment] 2020-09-05 22:30
Oh I thought the first argument is the destination

**Comment by MrGeorgen** [comment] 2020-09-05 22:38
I changed the line to `            call(["cp", "-r" , var.modprobeDirectory, var.temp + var.modprobeDirectory])` and it copied correctly. Now I get the same erroe for other copies as well, but I guess if I it to use the `cp` too it should work

**Comment by fearedbliss** [comment] 2020-09-05 23:14
That sounds good, I'm not against switching the `shutil.copytree` to a regular shell command. There are a few other references I'll need to adjust but I should have a test branch for you to play with soon.

**Comment by fearedbliss** [comment] 2020-09-06 00:18
Alright, I have a fix.

Can you check out the **`copyfix`** branch and try to build the initramfs. It should work.

`git clone https://github.com/fearedbliss/bliss-initramfs.git -b copyfix`

**Comment by fearedbliss** [comment] 2020-09-06 12:12
Hey, I already did all the work yesterday and posted instructions on how to get and test it. There are a lot more changes and references than updating the two copytree references.

**Closed** 2020-09-06 12:12 UTC

**Comment by MrGeorgen** [comment] 2020-09-06 12:27
Yeah I saw it after creating the pull request. Your fix works perfectly fine. Somehow the problem only `shutil.copytree`, other `shutil` calls work fine, so just changing the two lines also works. But your version looks cleaner and you already did the work anyway, so I'm happy with that

**Comment by fearedbliss** [comment] 2020-09-06 13:44
Haha yea I figured that’s what happened.  I’m glad it works for you and I’ll be making a release either later today or tomorrow to the Gentoo tree.

The reason I wanted to replace all the calls was because you may get errors in other situations as well that we may not be taking into account. So I would rather have one specific implementation used across all copy and delete calls as oppose to a combination of UNIX calls and Python shutil calls.

**Comment by MrGeorgen** [comment] 2020-09-06 15:34
Thanks for being so friendly although it is a bedrock linux issue. I will likely inspect this further and report this issue to the bedrock developers

**Comment by fearedbliss** [comment] 2020-09-06 20:21
@MrGeorgen Not a problem! Glad to have helped. Enjoy your weekend.

**Comment by fearedbliss** [comment] 2020-09-06 20:30
Just pushed 9.3.0 to the portage tree:

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=fe97ca1824ff795d88d1f75fc8bef9c82636b68b
